name: Node.js CICD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      
      - name: Install dependencies
        run: npm install
      
      - name: Test
        run: npm run test
  # deploy:
  #   runs-on: ubuntu-latest
  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  #   steps:
  #     # Check out the repository in the runner
  #     - uses: actions/checkout@v3
      
  #     # Install Python 3.9
  #     - name: Install Python 3.9
  #     uses: actions/setup-python@v3
  #     with:
  #         python-version: 3.9
      
  #     # Install the EB CLI using pip
  #     - name: Install EB CLI
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install awsebcli
      
  #     # Deploy to EB
  #     - name: Deploy to Elastic Beanstalk
  #       run: |
  #         eb deploy


  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set env to prod
  #       run: NODE_ENV=prod

  #     - name: Generate deployment package
  #       run: zip -r deploy.zip . -x '*.git*'
      
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-northeast-1
      
  #     - name: Copy to S3 bucket
  #       run: aws s3 cp deploy.zip s3://elasticbeanstalk-ap-northeast-1-121871211535
      
  #     - name: Print done message
  #       run: echo "CD pipeline finished success"
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: project-cs3219
          environment_name: Projectcs3219-env
          region: ap-northeast-1
          deployment_package: deploy.zip